Parameters:
  pInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  pBucketName:
    Type: String
    Description: Provide the bucket name which should be unique
  pEc2ImageId:
    Type: String
    Description: Provide the bucket name which should be unique

Resources: 
  rInstance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: !Ref pInstanceType
      ImageId: !Ref pEc2ImageId

  rS3Bkt:
    DependsOn:
      - "rInstance"
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: !Ref pBucketName
